package vm

type vm_instruction func(vm *VM)

func vm_noop(vm *VM)                        {}
func vm_push_nil(vm *VM)                    {}
func vm_push_true(vm *VM)                   {}
func vm_push_false(vm *VM)                  {}
func vm_push_int(vm *VM)                    {}
func vm_push_self(vm *VM)                   {}
func vm_set_literal(vm *VM)                 {}
func vm_push_literal(vm *VM)                {}
func vm_goto(vm *VM)                        {}
func vm_goto_if_false(vm *VM)               {}
func vm_goto_if_true(vm *VM)                {}
func vm_ret(vm *VM)                         {}
func vm_swap_stack(vm *VM)                  {}
func vm_dup_top(vm *VM)                     {}
func vm_dup_many(vm *VM)                    {}
func vm_pop(vm *VM)                         {}
func vm_pop_many(vm *VM)                    {}
func vm_rotate(vm *VM)                      {}
func vm_move_down(vm *VM)                   {}
func vm_set_local(vm *VM)                   {}
func vm_push_local(vm *VM)                  {}
func vm_push_local_depth(vm *VM)            {}
func vm_set_local_depth(vm *VM)             {}
func vm_passed_arg(vm *VM)                  {}
func vm_push_current_exception(vm *VM)      {}
func vm_clear_exception(vm *VM)             {}
func vm_push_exception_state(vm *VM)        {}
func vm_restore_exception_state(vm *VM)     {}
func vm_raise_exc(vm *VM)                   {}
func vm_setup_unwind(vm *VM)                {}
func vm_pop_unwind(vm *VM)                  {}
func vm_raise_return(vm *VM)                {}
func vm_ensure_return(vm *VM)               {}
func vm_raise_break(vm *VM)                 {}
func vm_reraise(vm *VM)                     {}
func vm_make_array(vm *VM)                  {}
func vm_cast_array(vm *VM)                  {}
func vm_shift_array(vm *VM)                 {}
func vm_set_ivar(vm *VM)                    {}
func vm_push_ivar(vm *VM)                   {}
func vm_push_const(vm *VM)                  {}
func vm_set_const(vm *VM)                   {}
func vm_set_const_at(vm *VM)                {}
func vm_find_const(vm *VM)                  {}
func vm_push_cpath_top(vm *VM)              {}
func vm_push_const_fast(vm *VM)             {}
func vm_find_const_fast(vm *VM)             {}
func vm_set_call_flags(vm *VM)              {}
func vm_allow_private(vm *VM)               {}
func vm_send_method(vm *VM)                 {}
func vm_send_stack(vm *VM)                  {}
func vm_send_stack_with_block(vm *VM)       {}
func vm_send_stack_with_splat(vm *VM)       {}
func vm_send_super_stack_with_block(vm *VM) {}
func vm_send_super_stack_with_splat(vm *VM) {}
func vm_push_block(vm *VM)                  {}
func vm_passed_blockarg(vm *VM)             {}
func vm_create_block(vm *VM)                {}
func vm_cast_for_single_block_arg(vm *VM)   {}
func vm_cast_for_multi_block_arg(vm *VM)    {}
func vm_cast_for_splat_block_arg(vm *VM)    {}
func vm_yield_stack(vm *VM)                 {}
func vm_yield_splat(vm *VM)                 {}
func vm_string_append(vm *VM)               {}
func vm_string_build(vm *VM)                {}
func vm_string_dup(vm *VM)                  {}
func vm_push_scope(vm *VM)                  {}
func vm_add_scope(vm *VM)                   {}
func vm_push_variables(vm *VM)              {}
func vm_check_interrupts(vm *VM)            {}
func vm_yield_debugger(vm *VM)              {}
func vm_is_nil(vm *VM)                      {}
func vm_check_serial(vm *VM)                {}
func vm_check_serial_private(vm *VM)        {}
func vm_push_my_field(vm *VM)               {}
func vm_store_my_field(vm *VM)              {}
func vm_kind_of(vm *VM)                     {}
func vm_instance_of(vm *VM)                 {}
func vm_meta_push_neg_1(vm *VM)             {}
func vm_meta_push_0(vm *VM)                 {}
func vm_meta_push_1(vm *VM)                 {}
func vm_meta_push_2(vm *VM)                 {}
func vm_meta_send_op_plus(vm *VM)           {}
func vm_meta_send_op_minus(vm *VM)          {}
func vm_meta_send_op_equal(vm *VM)          {}
func vm_meta_send_op_lt(vm *VM)             {}
func vm_meta_send_op_gt(vm *VM)             {}
func vm_meta_send_op_tequal(vm *VM)         {}
func vm_meta_send_call(vm *VM)              {}
func vm_push_my_offset(vm *VM)              {}
func vm_zsuper(vm *VM)                      {}
func vm_push_block_arg(vm *VM)              {}
func vm_push_undef(vm *VM)                  {}
func vm_push_stack_local(vm *VM)            {}
func vm_set_stack_local(vm *VM)             {}
func vm_push_has_block(vm *VM)              {}
func vm_push_proc(vm *VM)                   {}
func vm_check_frozen(vm *VM)                {}
func vm_cast_multi_value(vm *VM)            {}
func vm_invoke_primitive(vm *VM)            {}
func vm_push_rubinius(vm *VM)               {}
func vm_call_custom(vm *VM)                 {}
func vm_meta_to_s(vm *VM)                   {}
func vm_push_type(vm *VM)                   {}
func vm_push_mirror(vm *VM)                 {}
